### ISSUE TITLE
Auto completion with working with ">"

### ISSUE THREAD

**Issue by enwin** [jakobploens/Kirby-CMS-Auto-completion-for-Sublime-Text-2#1]
In order to keep the auto-completion tab open after typing ">" you need to edit your sublime preference file and add this line to the json :

``` javascript
"word_separators": "./\\\"'-:,.;<~!@#$%^&*|+=[]{}`~?"
```

this will disable the global pattern that includes ">", "(" and ")".

Unfortunately this is a global setting that might apply to all the auto-complete tabs.

**Comment by jakobploens** [comment]
Thanks for this one, I'll add it to the readme in a new version.
