### ISSUE TITLE
Package Control in ST

### ISSUE THREAD

**Issue by j-mes** [jakobploens/Kirby-CMS-Auto-completion-for-Sublime-Text-2#2]
Will this be added to Package Control in Sublime Text? It seems too good to not to be added to that for the hordes of clever folks using ST ;)

**Comment by jakobploens** [comment]
As I did not work on this for more than one year, I think I won't add this one to Package Control. But with Kirby 2 (which hopefully will be announced soon) I think I will build this one new, do more promotion and add it to Package Control. Promised! :)
